---
- hosts: all
  user: root
  become: yes
  connection: ssh

  vars:
          pkgname: apache2

  tasks:
          - name: Install PackageApache2
            action: yum name="{{pkgname}}" state=present
